package gui.view;

import cn.hutool.core.date.DateUtil;
import cn.hutool.core.thread.ThreadUtil;
import cn.hutool.core.util.StrUtil;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import util.MyUpdateUtil;

import javax.swing.*;
import java.awt.*;
import java.util.HashMap;

/**
 * @author yagol
 * @TIME 2021/11/22 - 8:03 下午
 * @Description PWC更新界面
 **/
public class UpdateGui implements BaseGui {
    private JFrame jFrame;

    @Override
    public void start(HashMap<String, Object> data) {

    }

    @Override
    public UpdateGui init() {
        jFrame = new JFrame("UpdateGui");
        jFrame.setContentPane(updatePanel);
        jFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        jFrame.pack();
        return this;
    }

    @Override
    public void show() {
        jFrame.setVisible(true);
        ThreadUtil.execute(new Runnable() {
            @Override
            public void run() {
                updateLogTextArea.append(DateUtil.now() + StrUtil.SPACE + "已开始搜索GitHub");
                downloadUpdateFile();
            }
        });
    }

    private void downloadUpdateFile() {
        try {
            MyUpdateUtil myUpdateUtil = new MyUpdateUtil();
            myUpdateUtil.checkUpdate(updateProgressBar, updateLogTextArea);
        } catch (Exception e) {
            updateLogTextArea.append(DateUtil.now() + StrUtil.SPACE + "下载更新文件时出现错误，错误信息为：" + e.getMessage());
            e.printStackTrace();
        }
    }

    @Override
    public void initComponentFunctions() {

    }


    private JPanel updatePanel;
    private JProgressBar updateProgressBar;
    private JTextArea updateLogTextArea;
    private JLabel updateLabel;
    private JLabel updateLogLabel;
    private JButton update;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        updatePanel = new JPanel();
        updatePanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        updatePanel.setPreferredSize(new Dimension(600, 200));
        updateLabel = new JLabel();
        updateLabel.setText("下载进度");
        updatePanel.add(updateLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        updateProgressBar = new JProgressBar();
        updatePanel.add(updateProgressBar, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        updateLogTextArea = new JTextArea();
        updateLogTextArea.setEditable(false);
        updatePanel.add(updateLogTextArea, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        updateLogLabel = new JLabel();
        updateLogLabel.setText("日志");
        updatePanel.add(updateLogLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return updatePanel;
    }

}
